package app.dc8.axonthin.eventstore

import app.dc8.axonthin.ThinAxonProperties
import app.dc8.axonthin.api.PayloadStorage
import org.slf4j.LoggerFactory
import org.springframework.jdbc.core.JdbcTemplate
import org.springframework.jdbc.support.JdbcUtils
import java.sql.DatabaseMetaData
import javax.sql.DataSource

/**
 * The event store's own schema check / setup (`axon.thin.event-store.schema`):
 * - `create-if-missing` creates the event and snapshot tables (with the unique index on aggregate id + sequence) and
 *   the `global_index` sequence when they do not exist — never alters or drops anything — then validates;
 * - `validate` checks tables, columns, the unique index (Hibernate's validation cannot) and the sequence increment,
 *   and fails startup listing every problem.
 *
 * H2 and PostgreSQL are supported for creation; validation works on any database with `information_schema`.
 */
internal class EventStoreSchema(
    private val dataSource: DataSource,
    private val config: ThinAxonProperties.EventStore,
) {
    private val log = LoggerFactory.getLogger(EventStoreSchema::class.java)
    private val jdbc = JdbcTemplate(dataSource)
    private val product = JdbcUtils.extractDatabaseMetaData(dataSource, DatabaseMetaData::getDatabaseProductName)
    private val postgres = product.contains("PostgreSQL", ignoreCase = true)

    private val eventTable = config.domainEventTableName
    private val snapshotTable = config.snapshotEventTableName
    private val usesSequence = config.globalIndex.strategy == ThinAxonProperties.GlobalIndex.Strategy.SEQUENCE
    private val sequence = config.globalIndex.sequenceName ?: "${eventTable}_seq"

    fun apply(mode: ThinAxonProperties.SchemaMode) {
        when (mode) {
            ThinAxonProperties.SchemaMode.NONE -> return
            ThinAxonProperties.SchemaMode.CREATE_IF_MISSING -> {
                createIfMissing()
                validate()
            }
            ThinAxonProperties.SchemaMode.VALIDATE -> validate()
        }
    }

    // ---- create ---------------------------------------------------------------------------------------------------

    private fun createIfMissing() {
        val storage = config.payloadColumn.storage ?: PayloadStorage.BINARY
        val payloadType = columnType(storage)
        if (usesSequence && !sequenceExists()) {
            jdbc.execute("create sequence $sequence start with 1 increment by ${config.globalIndex.allocationSize}")
            log.info("Created sequence {} (increment {})", sequence, config.globalIndex.allocationSize)
        }
        if (!tableExists(eventTable)) {
            val globalIndex = if (usesSequence) "bigint not null" else "bigint generated by default as identity"
            jdbc.execute(
                """
                create table $eventTable (
                    global_index         $globalIndex,
                    sequence_number      bigint       not null,
                    aggregate_identifier varchar(255) not null,
                    event_identifier     varchar(255) not null unique,
                    payload_revision     varchar(255),
                    payload_type         varchar(255) not null,
                    time_stamp           varchar(255) not null,
                    type                 varchar(255),
                    meta_data            $payloadType,
                    payload              $payloadType not null,
                    primary key (global_index),
                    constraint ${constraintName(eventTable)} unique (aggregate_identifier, sequence_number)
                )
                """.trimIndent(),
            )
            log.info("Created table {} (payload as {})", eventTable, payloadType)
        }
        if (!tableExists(snapshotTable)) {
            jdbc.execute(
                """
                create table $snapshotTable (
                    sequence_number      bigint       not null,
                    aggregate_identifier varchar(255) not null,
                    event_identifier     varchar(255) not null unique,
                    payload_revision     varchar(255),
                    payload_type         varchar(255) not null,
                    time_stamp           varchar(255) not null,
                    type                 varchar(255) not null,
                    meta_data            $payloadType,
                    payload              $payloadType not null,
                    primary key (sequence_number, aggregate_identifier, type)
                )
                """.trimIndent(),
            )
            log.info("Created table {} (payload as {})", snapshotTable, payloadType)
        }
    }

    private fun columnType(storage: PayloadStorage): String = when (storage) {
        PayloadStorage.BINARY -> if (postgres) "bytea" else "blob"
        PayloadStorage.TEXT -> if (postgres) "text" else "clob"
        PayloadStorage.OID -> if (postgres) "oid" else error("oid payload columns exist on PostgreSQL only (database: $product)")
    }

    private fun constraintName(table: String) = "${table.substringAfterLast('.')}_aggregate_seq".take(63)

    // ---- validate -------------------------------------------------------------------------------------------------

    private fun validate() {
        val problems = ArrayList<String>()
        for ((table, required) in listOf(eventTable to EVENT_COLUMNS, snapshotTable to SNAPSHOT_COLUMNS)) {
            val columns = columnsOf(table)
            if (columns.isEmpty()) {
                problems += "table $table does not exist"
                continue
            }
            (required - columns).takeIf { it.isNotEmpty() }?.let { problems += "table $table lacks columns $it" }
            config.payloadColumn.storage?.let { forced ->
                val detected = PayloadStorage.detect(dataSource, table, "payload")
                if (detected != forced) problems += "$table.payload is stored as $detected, but payload-column is $forced"
            }
        }
        if (columnsOf(eventTable).isNotEmpty() && !hasUniqueIndex(eventTable, setOf("aggregate_identifier", "sequence_number"))) {
            problems += "table $eventTable has no unique index on (aggregate_identifier, sequence_number) — " +
                "concurrent writers would corrupt aggregate streams (an orm.xml <table> override drops Axon's own index)"
        }
        if (usesSequence) {
            when (val increment = sequenceIncrement()) {
                null -> problems += "sequence $sequence does not exist (axon.thin.event-store.global-index.sequence-name)"
                config.globalIndex.allocationSize.toLong() -> Unit
                else -> problems += "sequence $sequence increments by $increment, but " +
                    "axon.thin.event-store.global-index.allocation-size is ${config.globalIndex.allocationSize} — they must be equal"
            }
        }
        check(problems.isEmpty()) {
            "axon-thin event store schema is invalid (axon.thin.event-store.schema):\n" + problems.joinToString("\n") { " - $it" }
        }
        log.info("Event store schema valid: {}, {}{}", eventTable, snapshotTable, if (usesSequence) ", $sequence" else "")
    }

    // ---- metadata -------------------------------------------------------------------------------------------------

    private fun split(table: String) = if ('.' in table) table.substringBefore('.') to table.substringAfter('.') else null to table

    private fun tableExists(table: String) = columnsOf(table).isNotEmpty()

    private fun columnsOf(table: String): Set<String> {
        val (schema, name) = split(table)
        val sql = "select column_name from information_schema.columns where upper(table_name) = upper(?)" +
            (if (schema != null) " and upper(table_schema) = upper(?)" else "")
        val args = listOfNotNull(name, schema).toTypedArray()
        return jdbc.queryForList(sql, String::class.java, *args).map { it.lowercase() }.toSet()
    }

    private fun hasUniqueIndex(table: String, columns: Set<String>): Boolean = dataSource.connection.use { connection ->
        val meta = connection.metaData
        val (schema, name) = split(table)
        val adjust: (String?) -> String? = { s ->
            when {
                s == null -> null
                meta.storesUpperCaseIdentifiers() -> s.uppercase()
                meta.storesLowerCaseIdentifiers() -> s.lowercase()
                else -> s
            }
        }
        val indexes = HashMap<String, MutableSet<String>>()
        meta.getIndexInfo(null, adjust(schema), adjust(name), true, false).use { rs ->
            while (rs.next()) {
                val index = rs.getString("INDEX_NAME") ?: continue
                val column = rs.getString("COLUMN_NAME") ?: continue
                indexes.getOrPut(index) { HashSet() } += column.lowercase()
            }
        }
        indexes.values.any { it == columns }
    }

    private fun sequenceExists() = sequenceIncrement() != null

    private fun sequenceIncrement(): Long? {
        val (schema, name) = split(sequence)
        val sql = "select increment from information_schema.sequences where upper(sequence_name) = upper(?)" +
            (if (schema != null) " and upper(sequence_schema) = upper(?)" else "")
        return jdbc.queryForList(sql, String::class.java, *listOfNotNull(name, schema).toTypedArray())
            .firstOrNull()?.trim()?.toLong()
    }

    private companion object {
        val EVENT_COLUMNS = setOf(
            "global_index", "event_identifier", "aggregate_identifier", "sequence_number", "type",
            "payload_type", "payload_revision", "payload", "meta_data", "time_stamp",
        )
        val SNAPSHOT_COLUMNS = EVENT_COLUMNS - "global_index"
    }
}
